services:
  postgres:
    image: postgres:16-alpine
    container_name: exam-portal-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - exam-portal-pgdata:/var/lib/postgresql/data

volumes:
  exam-portal-pgdata:
